// English Flashcard Data
const CARDS = [
  {word:"serendipity",phonetic:"/ˌserənˈdɪpɪti/",translation:"意外之喜，偶然发现",category:"情感",example:"Finding that book was pure serendipity.",exampleZh:"找到那本书纯属意外之喜。"},
  {word:"procrastinate",phonetic:"/prəˈkræstɪneɪt/",translation:"拖延，推迟",category:"行为",example:"Stop procrastinating and start your homework.",exampleZh:"别再拖延了，开始做作业吧。"},
  {word:"resilience",phonetic:"/rɪˈzɪliəns/",translation:"韧性，恢复力",category:"品格",example:"Her resilience helped her overcome every obstacle.",exampleZh:"她的韧性帮助她克服了每一个障碍。"},
  {word:"eloquent",phonetic:"/ˈeləkwənt/",translation:"口才好的，雄辩的",category:"描述",example:"He gave an eloquent speech at the graduation.",exampleZh:"他在毕业典礼上发表了一篇雄辩的演讲。"},
  {word:"meticulous",phonetic:"/məˈtɪkjələs/",translation:"一丝不苟的，细心的",category:"描述",example:"She was meticulous about every detail.",exampleZh:"她对每一个细节都一丝不苟。"},
  {word:"ambiguous",phonetic:"/æmˈbɪɡjuəs/",translation:"模棱两可的，不明确的",category:"描述",example:"The instructions were ambiguous and confusing.",exampleZh:"这些说明模棱两可，令人困惑。"},
  {word:"collaborate",phonetic:"/kəˈlæbəreɪt/",translation:"合作，协作",category:"行为",example:"We need to collaborate to finish this project.",exampleZh:"我们需要合作才能完成这个项目。"},
  {word:"innovative",phonetic:"/ˈɪnəveɪtɪv/",translation:"创新的，革新的",category:"描述",example:"The company is known for its innovative products.",exampleZh:"这家公司以其创新产品而闻名。"},
  {word:"perseverance",phonetic:"/ˌpɜːrsɪˈvɪərəns/",translation:"坚持，毅力",category:"品格",example:"Success requires perseverance and hard work.",exampleZh:"成功需要坚持和努力。"},
  {word:"enigmatic",phonetic:"/ˌenɪɡˈmætɪk/",translation:"神秘的，难以捉摸的",category:"描述",example:"She had an enigmatic smile on her face.",exampleZh:"她脸上带着神秘的微笑。"},
  {word:"negotiate",phonetic:"/nɪˈɡoʊʃieɪt/",translation:"谈判，协商",category:"商务",example:"We need to negotiate a better deal.",exampleZh:"我们需要谈判达成更好的协议。"},
  {word:"leverage",phonetic:"/ˈlevərɪdʒ/",translation:"利用，杠杆作用",category:"商务",example:"We can leverage social media for marketing.",exampleZh:"我们可以利用礼交媒体进行营销。"},
  {word:"stakeholder",phonetic:"/ˈsteɪkhoʊldər/",translation:"利益相关者",category:"商务",example:"All stakeholders must approve the plan.",exampleZh:"所有利益相关者必须批准该计划。"},
  {word:"benchmark",phonetic:"/ˈbentʃmɑːrk/",translation:"基准，参照标准",category:"商务",example:"Set a benchmark to measure your progress.",exampleZh:"设定一个基准来衡量你的进度。"},
  {word:"sustainable",phonetic:"/səˈsteɪnəbl/",translation:"可持续的，可维持的",category:"商务",example:"We need a sustainable business model.",exampleZh:"我们需要一个可持续的商业模式。"},
  {word:"algorithm",phonetic:"/ˈælɡərɪðəm/",translation:"算法",category:"科技",example:"The search algorithm ranks results by relevance.",exampleZh:"搜索算法按相关性对结果进行排序。"},
  {word:"infrastructure",phonetic:"/ˈɪnfrəstrʌktʃər/",translation:"基础设施",category:"科技",example:"Cloud infrastructure reduces hardware costs.",exampleZh:"云基础设施降低了硬件成本。"},
  {word:"encryption",phonetic:"/ɪnˈkrɪpʃən/",translation:"加密",category:"科技",example:"Encryption protects your personal data.",exampleZh:"加密可以保护你的个人数据。"},
  {word:"prototype",phonetic:"/ˈproʊtətaɪp/",translation:"原型，样机",category:"科技",example:"They built a prototype to test the idea.",exampleZh:"他们建造了一个原型来测试这个想法。"},
  {word:"autonomous",phonetic:"/ɔːˈtɑːnəməs/",translation:"自主的，自治的",category:"科技",example:"Autonomous vehicles can drive without human input.",exampleZh:"自动驾驶车辆无需人工操控即可行驶。"},
  {word:"hypothesis",phonetic:"/haɪˈpɒθɪsɪs/",translation:"假设，假说",category:"学术",example:"The scientist tested her hypothesis with experiments.",exampleZh:"这位科学家通过实验验证了她的假设。"},
  {word:"empirical",phonetic:"/ɪmˈpɪrɪkəl/",translation:"实证的，经验的",category:"学术",example:"The study provides empirical evidence for the theory.",exampleZh:"该研究为这一理论提供了实证依据。"},
  {word:"paradigm",phonetic:"/ˈpærədaɪm/",translation:"范式，典范",category:"学术",example:"This discovery created a new scientific paradigm.",exampleZh:"这一发现创造了一种新的科学范式。"},
  {word:"phenomenon",phonetic:"/fɪˈnɒmɪnən/",translation:"现象",category:"学术",example:"Lightning is a natural phenomenon.",exampleZh:"闪电是一种自然现象。"},
  {word:"coherent",phonetic:"/koʊˈhɪərənt/",translation:"连贯的，一致的",category:"学术",example:"Please write a coherent and structured essay.",exampleZh:"请写一篇条理清晰的文章。"},
  {word:"empathy",phonetic:"/ˈempəθi/",translation:"同理心，共情",category:"情感",example:"She showed great empathy for her patients.",exampleZh:"她对病人表现出极大的同理心。"},
  {word:"nostalgia",phonetic:"/nɒˈstældʒə/",translation:"怀旧，乡愁",category:"情感",example:"The old song filled him with nostalgia.",exampleZh:"那首老歌让他充满怀旧之情。"},
  {word:"melancholy",phonetic:"/ˈmelənkɒli/",translation:"忧郁，悲伤",category:"情感",example:"A feeling of melancholy settled over the room.",exampleZh:"一种忧郁的感觉笼罩了整个房间。"},
  {word:"euphoria",phonetic:"/juːˈfɔːriə/",translation:"欣快，极度愉悦",category:"情感",example:"She felt a sense of euphoria after winning.",exampleZh:"赢得胜利后她感到极度愉悦。"},
  {word:"integrity",phonetic:"/ɪnˈteɡrɪti/",translation:"诚信，正直",category:"品格",example:"Integrity is the foundation of trust.",exampleZh:"诚信是信任的基础。"},
  {word:"articulate",phonetic:"/ɑːrˈtɪkjuleɪt/",translation:"清楚地表达；口齿清晰的",category:"表达",example:"She could articulate her ideas very clearly.",exampleZh:"她能非常清楚地表达自己的想法。"},
  {word:"contemplate",phonetic:"/ˈkɒntəmpleɪt/",translation:"深思，考虑",category:"思考",example:"He sat quietly, contemplating his next move.",exampleZh:"他静静地坐着，思考着下一步行动。"},
  {word:"implement",phonetic:"/ˈɪmplɪment/",translation:"实施，执行",category:"行为",example:"The team will implement the new policy next week.",exampleZh:"团队将于下周实施新政策。"},
  {word:"facilitate",phonetic:"/fəˈsɪlɪteɪt/",translation:"促进，便利化",category:"行为",example:"Technology can facilitate better communication.",exampleZh:"技术可以促进更好的沟通。"},
  {word:"acknowledge",phonetic:"/əkˈnɒlɪdʒ/",translation:"承认，认可",category:"行为",example:"She acknowledged her mistake graciously.",exampleZh:"她大方地承认了自己的错误。"},
  {word:"ephemeral",phonetic:"/ɪˈfemərəl/",translation:"短暂的，转瞬即逝的",category:"描述",example:"Youth is ephemeral; cherish every moment.",exampleZh:"青春是短暂的，珍惜每一刻。"},
  {word:"ubiquitous",phonetic:"/juːˈbɪkwɪtəs/",translation:"无处不在的，普遍存在的",category:"描述",example:"Smartphones have become ubiquitous in modern life.",exampleZh:"智能手机在现代生活中已无处不在。"},
  {word:"pragmatic",phonetic:"/præɡˈmætɪk/",translation:"务实的，实际的",category:"描述",example:"We need a pragmatic approach to solve this problem.",exampleZh:"我们需要一种务实的方法来解决这个问题。"},
  {word:"sophisticated",phonetic:"/səˈfɪstɪkeɪtɪd/",translation:"复杂的；见多识广的",category:"描述",example:"The system uses sophisticated AI algorithms.",exampleZh:"该系统使用了复杂的AI算法。"},
  {word:"unprecedented",phonetic:"/ʌnˈpresɪdentɪd/",translation:"司无前例的，空前的",category:"描述",example:"The pandemic caused unprecedented economic disruption.",exampleZh:"这场疫情造成了史无前例的经济动荡。"}
];
